version: "3.9"

services:
  mysql_assignment_local:
    image: mysql:5.7.43
    platform: linux/amd64
    container_name: mysql_assignment_local
    environment:
      - LANG=C.UTF-8
      - MYSQL_DATABASE=assignmentdb
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=tester
      - MYSQL_ROOT_PASSWORD=root_password
    command:
      - --ssl=0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.volumes:/var/lib/mysql --user 1000
      - ./config/db:/docker-entrypoint-initdb.d
      - ./config:/etc/mysql/conf.d
    ports:
      - "3308:3306"
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
  es01:
    container_name: es01
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false # 보안 비활성화 설정
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic
  es02:
    container_name: es02
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false # 보안 비활성화 설정
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    container_name: es03
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false # 보안 비활성화 설정
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge